### PR TITLE
Added missing dependencies to coastsat-package

### PR DESCRIPTION
**Pull request by 2320sharon**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 2320sharon** [comment]
Hi @ocefpaf 
Thank you for creating the conda package for the coastsat-package. I realized that this package is missing the jupyterlab and geopandas packages , so I added them. I also added myself as a maintainer

**Comment by ocefpaf** [comment]
@2320sharon can you add those dependencies to the upstream metadata so the bot can perform auto-updates? It seems that they are missing at the moment, this is what we find in the pyproject.toml:

```toml
dependencies = [ "scikit-image",
 "earthengine-api>=0.1.304",
  "matplotlib",
  "astropy",
  "tqdm",
  "importlib-resources",
  "pyqt5",
  "scipy",
  "numpy"]
```

**Comment by 2320sharon** [comment]
Hey @ocefpaf
Thanks for noticing those missing dependencies. The reason I didn't include those dependencies in the pyproject.toml was because I didn't want to include them in the pip package because the official geopandas docs recommend only installing geopandas from conda instead of from pypi https://geopandas.org/en/stable/getting_started/install.html . 
By any chance do you know of a good way I can declare them as dependencies so that they can be included in the conda dependencies but not the pypi dependencies?

**Comment by ocefpaf** [comment]
> By any chance do you know of a good way I can declare them as dependencies so that they can be included in the conda dependencies but not the pypi dependencies?

We don't have an easy way to do that but, while geopandas does recommend that, unless both geopandas and jupyterlab are optional dependencies, they should be declared in the PyPI package too IMO or users will be getting an incomplete package, right?

PS: I'm pretty sure that the geopandas recommendation is outdated. It was mostly b/c of the rtree dependency and they replaced that functionality with shapely 2.0. Shapely does upload wheels and its installation via PyPI is OK.

**Comment by 2320sharon** [comment]
> PS: I'm pretty sure that the geopandas recommendation is outdated. It was mostly b/c of the rtree dependency and they replaced that functionality with shapely 2.0. Shapely does upload wheels and its installation via PyPI is OK.

You make a good point that users don't want an incomplete package plus it makes managing dependencies more difficult.
In that case, I'll add geopandas as a dependency to the pyproject.toml file.


I'm going to do a bit of research on if I should add jupyter lab as a pypi dependency as well. I think I safely can add it, but I want to double check.

**Comment by 2320sharon** [comment]
I see a few other packages similar to ours include it as a dependency. Most of them include it as a dev dependency but it should be fine.

**Comment by 2320sharon** [comment]
https://github.com/2320sharon/coastsat_package/releases/tag/v0.1.46
In coastsat_package v0.1.46 I added both packages to the the dependencies section in the pyproject.toml file
```
  "jupyterlab>=3.0.0",
  "geopandas",
```

**Pull request merged**
